// <auto-generated />
using System;
using Infrastructure.SQLServer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251222142301_AddRecommendationTable")]
    partial class AddRecommendationTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Input", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActivityLevel")
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<decimal>("HeightInches")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("HipInches")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NeckInches")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("WaistInches")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("WeightLbs")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_UserInput_CreatedAt");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_UserInput_UserId");

                    b.ToTable("UserInput", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Output", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BFP")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("BMI")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("BMR")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("CalculatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("InputId")
                        .HasColumnType("int");

                    b.Property<decimal>("LBM")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("TDEE")
                        .HasColumnType("decimal(18,4)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("WtHR")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("CalculatedAt")
                        .HasDatabaseName("IX_UserOutput_CalculatedAt");

                    b.HasIndex("InputId")
                        .HasDatabaseName("IX_UserOutput_InputId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_UserOutput_UserId");

                    b.ToTable("UserOutput", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Recommendation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BfpRecommendation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BmiRecommendation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BmrRecommendation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LbmRecommendation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TdeeRecommendation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("WtHrRecommendation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_UserRecommendation_UserId");

                    b.ToTable("UserRecommendation", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Output", b =>
                {
                    b.HasOne("Domain.Entities.Input", "Input")
                        .WithMany("Outputs")
                        .HasForeignKey("InputId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Input");
                });

            modelBuilder.Entity("Domain.Entities.Input", b =>
                {
                    b.Navigation("Outputs");
                });
#pragma warning restore 612, 618
        }
    }
}

